---
name: autocomplete_users_rate_limit
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368926
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/183244
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/523595
milestone: '17.10'
group: group::authentication
type: gitlab_com_derisk
default_enabled: false
