---
name: blob_repository_vue_header_app
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/509327
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/176182
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/513582
milestone: '17.9'
group: group::source code
type: gitlab_com_derisk
default_enabled: false
