---
name: force_cancel_build
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/467107
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/179137
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/519313
milestone: '17.10'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false

