---
name: parse_conan_metadata_on_upload
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/33892
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/178728
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/523693
milestone: '17.10'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
