---
name: secret_checks_for_web_requests
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/491282
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/178726
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/521677
milestone: '17.10'
group: group::secret detection
type: gitlab_com_derisk
default_enabled: false
