---
name: users_search_scoped_to_authorized_namespaces_basic_search_by_ids
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/442091
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/182557
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/524297
milestone: '17.10'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
