include:
  - template: Verify/Browser-Performance.gitlab-ci.yml

browser_performance:
  extends:
    - .default-retry
    - .review:rules:review-performance
  image: ${GITLAB_DEPENDENCY_PROXY_ADDRESS}docker:${DOCKER_VERSION}-git
  services:
    - docker:${DOCKER_VERSION}-dind
  stage: qa
  needs: ["review-deploy"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    URL: environment_url.txt
